<?php
if (!function_exists('wp_handle_upload')) {
  require_once(ABSPATH . 'wp-admin/includes/image.php');
  require_once(ABSPATH . 'wp-admin/includes/file.php');
  require_once(ABSPATH . 'wp-admin/includes/media.php');
}
?>

<?php get_header(); ?>
<?php // $current_user = get_current_user_id(); 
?>
<?php // echo $current_user; 
?>
<?php
// $args = array(
//   'author'        =>  $current_user->ID,
//   'orderby' => 'post_date',
//   'order'         =>  'ASC',
//   'posts_per_page' => 1,
//   'post_type' => 'case'
// );
// $case = get_posts($args)[0];
// if ($_FILES['avatar']) {
//   $photo = media_handle_upload('avatar', $case->ID);
// }
?>
<?php
// wp_update_user(array(
//   'ID' => $current_user->ID,
//   'first_name' => $_POST['first_name'],
//   'last_name' => $_POST['last_name'],
//   'user_email' => $_POST['email']
// ));
// unset($_POST['first_name']);
// unset($_POST['last_name']);
// unset($_POST['email']);
// unset($_POST['user_number']);
// unset($_POST['user_email']);
// foreach ($_POST as $key => $value) :
//   update_field($key, $value, $case->ID);
// endforeach;
?>

<?php


// $uploadedfile = $_FILES['avatar'];

// /* You can use wp_check_filetype() function to check the
// file type and go on wit the upload or stop it.*/

// $movefile = wp_handle_upload( $uploadedfile, array( 'test_form' => false ));

// if ( $movefile && !isset( $movefile['error'] ) ) {
// echo "File is valid, and was successfully uploaded.\n";
// var_dump( $movefile);
// // echo $movefile['url'];
// } else {
// /**
// * Error generated by _wp_handle_upload()
// * @see _wp_handle_upload() in wp-admin/includes/file.php
// */
// echo 'error';
// echo $movefile['error'];
// }
?>

<main role="main" aria-label="Content" class="bg-back-grey pt-8">
  <!-- section -->
  <section>

    <?php if (have_posts()) : while (have_posts()) : the_post(); ?>

        <!-- article -->
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
          <div class="doctor-registration bg-white my-12 max-w-6xl mx-auto py-12">
            <h2 class="text-pink text-center mb-16">Submission Details</h2>
            <form enctype="multipart/form-data" action="/update-profile" method="POST">
              <h3 class="w-full max-w-4xl">Patient Information</h3>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Patient Case Number</label>
                  <input type="text" name="patient_case_number" value="<?php echo get_field('patient_case_number', $case->ID); ?>" />
                </div>
                <div class="wp-block-column flex flex-col"">
                <label class=" text-h5-grey uppercase text-xs font-bold">Classification</label>
                  <div class="select">
                    <select name="classification">
                      <?php foreach (get_terms('classification', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Patient Gender</label>
                  <div class="select">
                    <select name="gender">
                      <?php foreach (get_terms('gender', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>

                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Level of Difficulty</label>
                  <div class="select">
                    <select name="level_of_difficulty">
                      <?php foreach (get_terms('level_of_difficulty', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Patient Date of Birth</label>
                  <input type="date" name="patient_birth_date" value="<?php echo get_field('patient_birth_date', $case->ID); ?>" />
                </div>

                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Treatment Option</label>
                  <div class="select">
                    <select name="level_of_difficulty">
                      <?php foreach (get_terms('treatment_option', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Numb1er of Aligner Sets</label>
                  <div class="select">
                    <select name="number_of_aligner_sets">
                      <?php foreach (get_terms('number_of_aligner_sets', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>

                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Wear Schedule</label>
                  <div class="select">
                    <select name="wear_schedule">
                      <?php foreach (get_terms('wear_schedule', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
              <div class="max-w-4xl mx-auto">
                <label class=" text-h5-grey uppercase text-xs font-bold">Primary Complaint</label>
                <textarea name="primary_complaint"></textarea>
              </div>
              <h3 class="w-full max-w-4xl">Treatment Summary</h3>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Submission Materials</label>
                  <div class="select">
                    <select name="submission_materials">
                      <?php foreach (get_terms('submission_materials', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>

                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Type of Retention</label>
                  <div class="select">
                    <select name="type_of_retention">
                      <?php foreach (get_terms('type_of_retention', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Aligner Material</label>
                  <div class="select">
                    <select name="aligner_materioal">
                      <?php foreach (get_terms('aligner_material', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>

                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Other Products Used (Optional)</label>
                  <div class="select">
                    <select name="other_products_used">
                      <?php foreach (get_terms('other_products_used', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Number of Revisions</label>
                  <div class="select">
                    <select name="number_of_revisions">
                      <?php foreach (get_terms('number_of_revisions', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>

                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Total Treatment Time</label>
                  <div class="select">
                    <select name="type_of_retention">
                      <?php foreach (get_terms('total_treatment_time', array('hide_empty' => false)) as $term) : ?>
                        <option><?php echo $term->name; ?></option>
                      <?php endforeach; ?>
                    </select>
                  </div>
                </div>
              </div>

              <div class="max-w-4xl mx-auto">
                <label class=" text-h5-grey uppercase text-xs font-bold">Reason for Revision (Optional)</label>
                <textarea name="reason_for_revision"></textarea>
              </div>
              <div class="max-w-4xl mx-auto">
                <label class=" text-h5-grey uppercase text-xs font-bold">Clinical Conditions</label>
                <?php foreach (get_terms('technical_condition', array('hide_empty' => false)) as $term) : ?>
                  <div class="flex items-center">
                    <input class="mr-2" type="checkbox" value="<?php echo $term->name; ?>" />
                    <p><?php echo $term->name; ?></p>
                  </div>
                <?php endforeach; ?>
              </div>
              <div class="max-w-4xl mx-auto">
                <label class=" text-h5-grey uppercase text-xs font-bold">Treatment Technique</label>
                <?php foreach (get_terms('treatment_technique', array('hide_empty' => false)) as $term) : ?>
                  <div class="flex items-center">
                    <input class="mr-2" type="checkbox" value="<?php echo $term->name; ?>" />
                    <p><?php echo $term->name; ?></p>
                  </div>
                <?php endforeach; ?>
              </div>
              <div class="max-w-4xl mx-auto mt-8">
                <label class=" text-h5-grey uppercase text-xs font-bold">Results Achieved</label>
                <textarea name="results_achieved"></textarea>
              </div>
              <div class="max-w-4xl mx-auto">
                <label class=" text-h5-grey uppercase text-xs font-bold">Additional Comments (Optional)</label>
                <textarea name="additional_comments"></textarea>
              </div>
              <div class="max-w-4xl mx-auto mt-8">
                <h3>Before Photos</h3>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('before_occluded_buccal_view_of_anterior', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of anterior</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('before_occluded_buccal_view_of_right_lateral', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of right lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('before_occluded_buccal_view_of_left_lateral', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of left lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('before_occlusal_view_of_upper', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occlusal view of upper</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('before_occlusal_view_of_lower', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occlusal view of lower</label>
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">

                  </div>
                </div>

              </div>
              <div class="max-w-4xl mx-auto mt-8">
                <h3>After Photos</h3>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('after_occluded_buccal_view_of_anterior', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of anterior</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('after_occluded_buccal_view_of_right_lateral', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of right lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('after_occluded_buccal_view_of_left_lateral', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of left lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('after_occlusal_view_of_upper', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occlusal view of upper</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('after_occlusal_view_of_lower', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occlusal view of lower</label>
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">

                  </div>
                </div>

              </div>
              <div class="max-w-4xl mx-auto mt-8">
                <h3>Progress Photos</h3>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('progress_occluded_buccal_view_of_anterior', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of anterior</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('progress_occluded_buccal_view_of_right_lateral', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of right lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('progress_occluded_buccal_view_of_left_lateral', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of left lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('progress_occlusal_view_of_upper', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occlusal view of upper</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('progress_occlusal_view_of_lower', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occlusal view of lower</label>
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">

                  </div>
                </div>

              </div>
              <div class="max-w-4xl mx-auto mt-8">
                <h3>Radiographs</h3>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('before_panoramic_x-ray', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of anterior</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('before_cephalometric_x-ray', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of right lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>
                <div class="wp-block-columns max-w-4xl mx-auto">
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('after_panoramic_x-ray', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occluded buccal view of left lateral</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                  <div class="wp-block-column flex flex-col">
                    <div class="flex items-center max-w-4xl mx-auto avatar">
                      <?php
                      $photo = get_field('after_cephalometric_x-ray', $case->ID);
                      if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/no_photo.png';
                      ?>
                      <img src="<?php echo $photo; ?>" />
                      <div class="flex flex-col">
                        <label class="text-h5-grey uppercase text-xs font-bold">Occlusal view of upper</label>
                        <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                      </div>
                    </div>
                  </div>
                </div>


              </div>


              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Practice Country</label>
                  <div class="select">
                    <select name="practice-country">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Practice Province/State</label>
                  <div class="select">

                    <select name="practice-state">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Practice Country</label>
                  <div class="select">
                    <select name="practice-country">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Practice Province/State</label>
                  <div class="select">

                    <select name="practice-state">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
              </div>




              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Address (Optional)</label>
                  <input type="text" name="address_1" value="<?php the_field('address_1', $case->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Second Address(Optional)</label>
                  <input type="text" name="address_2" value="<?php the_field('address_2', $case->ID); ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">City (Optional)</label>
                  <input type="text" name="city" value="<?php the_field('city', $case->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Zip/Postal Code (Optional)</label>
                  <input type="text" name="zip" value="<?php the_field('zip', $case->ID); ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Practice Email (Optional)</label>
                  <input type="email" name="practice_email" value="<?php the_field('practice_email', $case->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Phone (optional)</label>
                  <input type="text" name="phone" value="<?php the_field('phone', $case->ID); ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Website (Optional)</label>
                  <input type="text" name="website" value="<?php the_field('website', $case->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col">
                </div>
              </div>






          </div>


          </div>
          </div>
          <div class=" max-w-4xl w-full mx-auto flex flex-col">

            <input type="submit" class="w-full max-w-xs bg-pink text-white text-sm uppercase mx-auto rounded my-12 py-4 font-bold" value="SUBMIT" />
          </div>

          </form>
          </div>


          <?php edit_post_link(); ?>

        </article>
        <!-- /article -->

      <?php endwhile; ?>

    <?php else : ?>

      <!-- article -->
      <article>

        <h2><?php _e('Sorry, nothing to display.', 'html5blank'); ?></h2>

      </article>
      <!-- /article -->

    <?php endif; ?>

  </section>
  <!-- /section -->
</main>
<?php get_footer(); ?>