<?php
if (!function_exists('wp_handle_upload')) {
  require_once(ABSPATH . 'wp-admin/includes/image.php');
  require_once(ABSPATH . 'wp-admin/includes/file.php');
  require_once(ABSPATH . 'wp-admin/includes/media.php');
}
?>

<?php get_header(); ?>
<?php // $current_user = get_current_user_id(); ?>
<?php // echo $current_user; ?>
<?php
$args = array(
  'author'        =>  $current_user->ID,
  'orderby' => 'post_date',
  'order'         =>  'ASC',
  'posts_per_page' => 1,
  'post_type'=>'doctor'
);
$doctor = get_posts($args);
$photo = media_handle_upload('avatar',$doctor->ID);
echo set_post_thumbnail($doctor->ID, $photo);
the_post_thumbnail($doctor->ID);

// $uploadedfile = $_FILES['avatar'];

// /* You can use wp_check_filetype() function to check the
// file type and go on wit the upload or stop it.*/

// $movefile = wp_handle_upload( $uploadedfile, array( 'test_form' => false ));

// if ( $movefile && !isset( $movefile['error'] ) ) {
// echo "File is valid, and was successfully uploaded.\n";
// var_dump( $movefile);
// // echo $movefile['url'];
// } else {
// /**
// * Error generated by _wp_handle_upload()
// * @see _wp_handle_upload() in wp-admin/includes/file.php
// */
// echo 'error';
// echo $movefile['error'];
// }
?>

<main role="main" aria-label="Content" class="bg-back-grey pt-8">
  <!-- section -->
  <section>

    <?php if (have_posts()) : while (have_posts()) : the_post(); ?>

        <!-- article -->
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
          <div class="doctor-registration bg-white my-12 max-w-6xl mx-auto py-12">
            <h2 class="text-pink text-center mb-16">Update Profile</h2>
            <form enctype="multipart/form-data" action="/update-profile" method="POST">
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Email</label>
                  <input type="email" name="email" />
                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">ClearCorrect User Number</label>
                  <input type="text" name="user_number" value="<?php echo $current_user->ID; ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">First Name</label>
                  <input type="text" name="first_name" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Last Name</label>
                  <input type="text" name="last_name" />

                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Degree</label>
                  <div class="select">
                    <select name="degree">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Specialty</label>
                  <div class="select">

                    <select name="specialty">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="flex items-center max-w-4xl mx-auto">
                <?php
                $photo = get_the_post_thumbnail_url($doctor->ID);
                if (empty($photo)) $photo = 'http://localhost:9009/wp-content/uploads/2021/01/avatar.png';
                ?>
                <img src="<?php echo $photo; ?>" />
                <div class="flex flex-col">
                  <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                  <label class="text-h5-grey uppercase text-xs font-bold">Profile Image (Optional)</label>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Practice Country</label>
                  <div class="select">
                    <select name="practice-country">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Practice Province/State</label>
                  <div class="select">

                    <select name="practice-state">
                      <option>Make Selection</option>
                      <option>One</option>
                      <option>Two</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Address (Optional)</label>
                  <input type="text" name="address_1" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Second Address(Optional)</label>
                  <input type="text" name="address_2" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">City (Optional)</label>
                  <input type="text" name="city" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Zip/Postal Code (Optional)</label>
                  <input type="text" name="zip" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Practice Email (Optional)</label>
                  <input type="email" name="user_email" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Phone (optional)</label>
                  <input type="text" name="phone" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Website (Optional)</label>
                  <input type="email" name="user_email" />

                </div>
                <div class="wp-block-column flex flex-col"">
                </div>
              </div>






          </div>


          </div>
          </div>
          <div class=" max-w-4xl w-full mx-auto flex flex-col">
                  <div class="flex items-center mb-4">
                    <div class="check-style-wrap">

                      <input class="checkbox" type="checkbox" name="terms-conditions" />
                    </div>

                    <div class="flex">
                      <div class="checkbox"></div>
                      <div class="flex flex-col">
                        <p>I confirm that I have read and agree to the ClearCorrect Case Gallery <a class="block" href="/terms-conditions">Terms & Conditions</a></p>
                      </div>
                    </div>
                  </div>
                  <div class="flex items-center">
                    <div class="check-style-wrap">
                      <input class="checkbox" type="checkbox" name="terms-conditions" />
                    </div>
                    <div class="flex">
                      <div class="checkbox"></div>
                      <div class="flex flex-col">
                        <p>I confirm that I have read and agree to the ClearCorrect Case Gallery <a class="block" href="/doctor-consent-agreement">Doctor Consent Agreement</a></p>
                      </div>
                    </div>
                  </div>
                  <input type="submit" class="w-full max-w-xs bg-pink text-white text-sm uppercase mx-auto rounded my-12 py-4 font-bold" value="SUBMIT" />
                  <a class="text-center mb-4" href="/login">I already have an account.</a>
                  <a class="text-center href=" /patient-register">I already have an account.</a>
                </div>

            </form>
          </div>


          <?php edit_post_link(); ?>

        </article>
        <!-- /article -->

      <?php endwhile; ?>

    <?php else : ?>

      <!-- article -->
      <article>

        <h2><?php _e('Sorry, nothing to display.', 'html5blank'); ?></h2>

      </article>
      <!-- /article -->

    <?php endif; ?>

  </section>
  <!-- /section -->
</main>
<?php get_footer(); ?>